### ISSUE TITLE
Sept 2018 Census - Active Characters Broken

### ISSUE THREAD

**Issue by matthewhillier** [XIVStats/XIVStats#33]
All the active character stats appear to be broken for the latest published census (Sept 2018).

![image](https://user-images.githubusercontent.com/10650436/46005618-3c374180-c0e8-11e8-988e-ad0dff4785d4.png)

**Comment by matthewhillier** [comment]
@Pricetx FYI

**Comment by Pricetx** [comment]
This has been resolved for now. It looks like the current live environment is not reading stats for active players correctly. 

As it happens, the old server was still running the census each month so i've stolen the HTML from that. In the next day or so I hope to put together a basic dev environment in AWS. Once that's working fine i'll move prod over as well.

**Comment by esotericist** [comment]
It looks like this is still a problem. At least I'm still seeing for all the active counts on the live site as of November.

**Comment by Pricetx** [comment]
This is linked to #35 . The version of the gatherer currently running in production is not capturing a list of minions and mounts. The active check is based on looking for the Yol mount. It is therefore producing 0 for anything involving an active check. 

Work is ongoing to update the gatherer to the latest version. However, this relies on https://github.com/XIVStats/XIVStats-Gatherer-Java/issues/37 being resolved first.

**Comment by matthewhillier** [comment]
Have reviewed XIVStats/XIVStats-Gatherer-Java#37 and I think this is a red-herring. I'd recommend verifying by running V2.0 of the gatherer along with the latest version of the PHP.

Assuming that the live gatherer is still running pre-2.0 code, then I think upgrading it to 2.0+ will solve this as it re-aligns the databases and ensures all fields are always available. Worst case, we drop the DB entirely and let the gatherer re-create.

**Comment by Pricetx** [comment]
There are no outstanding issues with the active count. This can be closed.
